### PR TITLE
Creating MMS Based Navigation for simple link headers or term driven fri...

### PR DESCRIPTION
**Pull request by ashuetawah**
This sample creates the MMS based navigation terms. Terms can be simple link headers or it can be term driven friendly URLs.

### CODE REVIEW

**Comment by jansenbe** [comment]
Thanks a lot for this contribution! 

Before we can accept your changes we would need to ask you to sign a [collaboration agreement](https://github.com/OfficeDev/PnP/blob/master/Microsoft%20Contribution%20License%20Agreement.docx). Can you please fill in the sections highlighted in yellow, sign it and send a scanned version to Office365PnP_CA@microsoft.com. This agreement only needs to be signed once, so for all your future pull requests you're fine. Sorry for the extra hassle, but it is a new requirement from the Microsoft legal department.

**Comment by ashuetawah** [comment]
I have just email id.

**Comment by jansenbe** [comment]
Thanks for this Ashish. I'm merging this right now...sorry for the delay but the team has been focused on site provisioning lately.

**Comment by jansenbe** [comment]
manually closing this PR since it was created against the master branch. Changes have been merged to our dev branch.

**Comment by ashuetawah** [comment]
Hi Bert,
Thanks for letting me know.I am thinking to clean the git of mine and start from scratch. is it safe now to delete my branches?
Thanks,Ashish

Date: Sun, 29 Mar 2015 11:22:12 -0700

**Comment by jansenbe** [comment]
Sure. The easiest way to start clean is by deleting your forked repo and creating a new one (also clean your local clones). If you've pending changes you should backup those.

**Pull request closed without merging**
