### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by NPrice99**
ObjectListInstance fix "Not Supported" error by instering AsEnumerable()

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Hi Nigel,

We only accept pull requests against the dev branch. Unfortunately this PR targets the master branch. Please reissue your pull request against the dev branch. I will close this PR now.

/Erwin

**Comment by NPrice99** [comment]
Hi Erwin

Everytime I click on “Pull Request” at the top of the page it says I want to merge dev and master.

I just want to update ObjectListInstance.cs but there is not pull request on that page.

Thanks

Nigel

**Comment by erwinvanhunen** [comment]
After you click on "Pull Request" you can switch from master to dev in the dropdown.

image

**Comment by erwinvanhunen** [comment]
Make also sure to review: https://github.com/OfficeDev/PnP/wiki/Preparing-a-contribution-and-letting-the-PnP-core-team-know-via-a-pull-request. It's mentioned there too how to target the correct branch.

**Pull request closed without merging**
