### PR TITLE
ExecuteQueryRetry for exception existing connection was forcibly closed by the remote host

### PR DESCRIPTION
**Pull request by nanddeepn**
We are also experiencing the SocketException: existing connection was forcibly closed by the remote host
Added a catch block to perform retry in the SocketException scenario.

Full error stack is here:
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

### CODE REVIEW

**Comment by ronnieholm** [comment]
I wonder if retrying on SocketException is always guaranteed to be safe?

Is it possible for the call to clientContext.ExecuteQuery() in the try block to be partially completed before the SocketException exception is thrown? Then retrying might cause another unrelated exception to be thrown which might be hard to debug because the SocketException wasn't strictly throttling related.

**Comment by nanddeepn** [comment]
Hi Ronnie, 
I am not too sure but "underlying connection was closed", means there is a possibility of pool recycle or any related event which errors out in ExecuteQuery. In such scenarios ExecuteQuery after a wait time seems to be working in our situation.

**Comment by hhtech1** [comment]
We are seeing several different variants of this "underlying connection was closed", each with a different "main" exception type:
Example 1:
Unhandled Exception: **System.AggregateException**: One or more errors occurred. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An **existing connection was forcibly closed** by the remote host
Example 2: 
Unhandled Exception: **System.IO.IOException**: Unable to read data from the transport connection: An **existing connection was forcibly closed** by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
Example 3 (same as above except main exception type):
Unhandled Exception: **System.Net.WebException**: The **underlying connection was closed**: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An **existing connection was forcibly closed** by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
Example 4 (different exception, but common is the "underlying connection was closed" message:
EXCEPTION: System.Net.WebException: The **underlying connection was closed**: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine

We are currently handling this by catching Exception and looking for string **underlying connection was closed** or **existing connection was forcibly closed** in Exception.Message. Not exactly ideal but haven't found a better solution yet.

**Comment by hhtech1** [comment]
Yet another one that should probably handled in ExecuteQueryRetry is the timeout situation:
EXCEPTION: System.Net.WebException: The operation has timed out.
   at System.Net.GZipWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.Read()
   at Microsoft.SharePoint.Client.TextPeekReader.Read()
   at Microsoft.SharePoint.Client.JsonReader.DecodeString(Int32 tokenPosition, Boolean isName)
   at Microsoft.SharePoint.Client.JsonReader.GetTokenPrivate()
   at Microsoft.SharePoint.Client.JsonReader.ReadToken()
   at Microsoft.SharePoint.Client.JsonReader.ReadString()
   at Microsoft.SharePoint.Client.ContentType.InitOnePropertyFromJson(String peekedName, JsonReader reader)
   at Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
   at Microsoft.SharePoint.Client.JsonReader.ReadJsonObject(Type fallbackType)
   at Microsoft.SharePoint.Client.JsonReader.ReadObject(Type fallbackType)
   at Microsoft.SharePoint.Client.JsonReader.ReadObjectArray(Type fallbackElementType)
   at Microsoft.SharePoint.Client.ClientObjectCollection`1.ReadChildItems(JsonReader reader)
   at Microsoft.SharePoint.Client.ClientObjectCollection.InitOnePropertyFromJson(String peekedName, JsonReader reader)
   at Microsoft.SharePoint.Client.ClientObject.FromJson(JsonReader reader)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
   at Microsoft.SharePoint.Client.FieldAndContentTypeExtensions.GetContentTypeById(Web web, String contentTypeId, Boolean searchInSiteHierarchy)
   at Microsoft.SharePoint.Client.FieldAndContentTypeExtensions.AddContentTypeToListById(List list, String contentTypeID, Boolean defaultContent, Boolean searchContentTypeInSiteHierarchy)

**Comment by ronnieholm** [comment]
What are you doing CSOM-wise to make these exceptions occur? A single CSOM call with time in between or hammering SharePoint Online? I'm hammering the API from an Azure VM and have never encountered anything but HTTP 503 during site collection creation.

Perhaps it's a tenant/physical machine issue.

**Comment by hhtech1** [comment]
We have a console application which deploys quite a lot of items to O365. It e.g. deploys site columns, content types, page layouts, web part definitions etc, and then creates a hierarchy of sites.

We run the console application manually from a developer machine or from a team build on our build server, so we have used several physical client machines, and also several O365 tenants.

We don't see these "underlying connection was closed" issues every time, but often enough that we need some way of handling them. The timeout is very rare.

**Comment by nanddeepn** [comment]
I see mostly System.Net.Sockets.SocketException nested inside System.IO.IOException or System.Net.WebException

**Comment by jansenbe** [comment]
@VesaJuvonen: let's find out why we the service throws "System.Net.WebException: The underlying connection was closed" exception. If this is a common thing then we'll need to have a look at how to mitigate this. 

@nanddeepn: once we've more clarity we'll decide what to do with this PR, but thanks already for letting us now!

**Comment by jansenbe** [comment]
We've been discussing this PR with the Office365 product group and based on their recommendations we're not going to capture additional exceptions as part of the PnP throttling handling. The main problem with just simply retrying is that an executequery command processes a batch of actions...if the error is thrown in middle of batch then just retrying will result in unexpected behavior as part of the actions were already done. 

In this case it's better to properly deal with the error and implement rollback logic and retry the complete batch. https://github.com/OfficeDev/PnP/tree/dev/Samples/Core.AppEvents.HandlerDelegation shows how this can be done.

**Comment by nanddeepn** [comment]
Thank you for the update Bert!

**Pull request closed without merging**
