### PR TITLE
Get the language agnostic pages library name

### PR DESCRIPTION
**Pull request by nanddeepn**
Currently, we get pages library as hard-coded EN value "Pages", which works only in EN sites.
Modified the code to get the pages library name in a language agnostic way.

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Thanks! I will look into it this afternoon (Swedish time).

**Comment by erwinvanhunen** [comment]
Thanks Nanddeep!

**Comment by nanddeepn** [comment]
Thank you Erwin!

**Comment by VesaJuvonen** [comment]
Thanks Nanddeep... Great add-on, which actually should have been there since day one, but better late than never. Good that you are working with some of those Scandinavian customers, so that we get these right approaches included also from multi-lingual perspective.

**Comment by nanddeepn** [comment]
Thank you @VesaJuvonen 
PnP has provided an excellent platform to share our project experiences with all. A big thank to you all.

**Pull request merged**
