### PR TITLE
Branding.js link

### PR DESCRIPTION
**Pull request by MartinHatch**
Spoke to Jeremy Thake and Vesa at the SharePoint Evolutions Conference, and they suggested I integrated all of my JSLink / client-rendering samples into the OfficeDev PnP Samples set.

So .. here it is :) I emailed over my signed compliance form yesterday.

This includes the initial cut of the Branding.JSLink samples. The Readme.md file is in reasonable shape and includes sine screenshots, and the sample code has all been tested. 

Thanks!

Martin

### CODE REVIEW

**Comment by MartinHatch** [comment]
Yep .. form was signed and emailed over yesterday, ahead of the curve on that one :)

**Comment by VesaJuvonen** [comment]
Thank Martin,
Team will have a look on this and not expecting any issues. Readme looks really good and thanks for your efforts on this one. We are definitely looking getting this included and verified by the time of the May master merge on 4th of May.

**Comment by jansenbe** [comment]
Appreciated Martin. I'll have a look at and perform the PR merging.

**Comment by jansenbe** [comment]
Hi Martin. I've been testing this and works nice...but seems to have problems with MDS. Can you check https://github.com/OfficeDev/PnP/tree/master/Samples/Branding.ClientSideRendering and apply similar changes to your sample so that the scripts do work with and without MDS enabled. If you can't do that then please let us know and we'll handle this.

**Comment by MartinHatch** [comment]
Aha of course! Ironically I was chatting to Wictor Wilén and Todd Bleeker about that at SPEvo .. It just wasn't part of the demo.

I'll get the code updated and push my changes in, if not over the weekend then early next week!

Martin

Sent from my Windows Phone
________________________________

**Comment by jansenbe** [comment]
Super :)

**Comment by VesaJuvonen** [comment]
If you Martin have a change, this would be great solution to demonstrate during our May community call. Next month that will be on 12th of May. You can find ICS for the monthly meeting from https://www.yammer.com/itpronetwork/uploaded_files/32112139. This would be 10-15 min demo to just demonstrate the functionality and it all get's recorded to our Channel 9 section. Works?

Up to you, but if you can't do that, we would like someone from Core team to do this, if you are fine.

**Comment by MartinHatch** [comment]
I'd be happy to! Lets queue it up 😊

Martin

Sent from my Windows Phone
________________________________

**Comment by MartinHatch** [comment]
Ok, I have updated the code with MDS support so that should all now be committed and pushed into my branch. Do I need to re-submit a new Pull Request?

**Comment by VesaJuvonen** [comment]
Please do, so that we get Git do the work for migration and we get updated files to PnP branch. Thx for the update.

**Pull request merged**
