### PR TITLE
Fix #812 - Fix PSMODULEPATH in PnP Powershell Commands wix installer

### LINKED ISSUE #812: Added path to psmodulepath is to short
The provided path when installing powershell commands is C:\Program Files\OfficeDevPnP.
This will make Powershell give an error when running commands.

C:\Program Files\OfficeDevPnP\PowerShell\Modules is the correct path.
Quickfix: change the environment value.

Long term: change the installer :)

### PR DESCRIPTION
**Pull request by ZeBobo5**

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
That's interesting, as this causes no issues for me. Given the hierarchy of the path PS will/should resolve the module anyway. The module is auto loaded the moment I enter one of the cmdlets in it.

$env:PSModulePath returns

```
C:\Users\erwin\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:
\Program Files\OfficeDevPnP\;C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement
```

Straight after opening PowerShell Get-Module returns:

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.6.0.0    Jump.Location                       {Get-JumpStatus, Set-JumpLocation}
Script     0.6.0      Jump.Location
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.0    PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSRead...
```

After entering Connect-SPOnline

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Binary     0.6.0.0    Jump.Location                       {Get-JumpStatus, Set-JumpLocation}
Script     0.6.0      Jump.Location
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Binary     1.0.0.0    OfficeDevPnP.PowerShell.Commands    {Add-SPOContentType, Add-SPOContentTypeToList, Add-SPOCustomAction, Add-SPOEventReceiver...
Binary     1.0.0.0    PSReadline                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandler, Set-PSRead...
```

Then if I check for the path of the module I see:

```
PS C:\> Get-Module OfficeDevPnP.PowerShell.Commands | select Path

Path
----
C:\Program Files\OfficeDevPnP\PowerShell\Modules\OfficeDevPnP.PowerShell.Commands\OfficeDevPnP.PowerShell.Commands.dll
```

**Comment by erwinvanhunen** [comment]
Can you please double check on your environment? I applied your proposed change to the setup and it actually fails on my environment. E.g. it adds the path as proposed to the PSModulePath environment variable, but PowerShell fails to resolve the module automatically. E.g. I'm inclined not to merge this pull request.

**Comment by jansenbe** [comment]
Given that the problem seems not to reproducible and the provided fix is generating new problems I'm going to close this PR for now. If later on this change needs to be revisited then we can simply open the PR again.

**Comment by PerOve** [comment]
I have the same experience with all computers I have setup. Both win 8.1, win 7 and win 10.
Installing is fine.
checking the psmodulepath in environmental settings:
c:\program files\officedevpnp is added at the end.
officedevpnp cmdlets is not available in Powershell ISE.

Changing the psmodulepath in environmental settings to:
c:\program files\officedevpnp\powershell\modules
officedevpnp is available in Powershell ISE

This step should be avoided.
And it is only a windows environmental setting that needs to be changed. nothing else.

**Pull request closed without merging**
