### PR TITLE
O365 DEV

### PR DESCRIPTION
**Pull request by sunilghelawat**

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Hi!

Thank you for your submission! However, you are targeting the master branch and we don't accept pull requests on that one. Please reissue your pull request towards the dev branch for us to evaluate it. I will close this PR now.

**Comment by sunilghelawat** [comment]
Hi Erwin,


I want to download the UserProfile.Manipulation.CSOM sample at https://github.com/OfficeDev/PnP/tree/master/Samples/UserProfile.Manipulation.CSOM


However I am not able to see any option to download the code. I am logged in the GitHub.


Can you please let me know how can I download the code. Thanks for your support.


Warm Regards,
Sunil Ghelawat


________________________________

**Comment by erwinvanhunen** [comment]
Hi Sunil,

Navigate here: https://github.com/OfficeDev/PnP. You'll see a "Download ZIP" button in the bottom of the menu at the right. This will download the repository code, including the sample you're looking for.

**Comment by sunilghelawat** [comment]
Thanks Erwin. You are legend.


Warm Regards,
Sunil Ghelawat


________________________________

**Pull request closed without merging**
