### PR TITLE
added AllowAllPageLayouts method (similar to SSOM)

### PR DESCRIPTION
**Pull request by vman**
Added AllowAllPageLayouts method (similar to SSOM) which will allow all the page layouts to be used on the web. The ClearAvailablePageLayouts method can be used to achieve the same functionality but then the name of the method does not seem meaningful

### CODE REVIEW

**Comment by jansenbe** [comment]
Good idea. I've merged this PR but made the old method obsolete and moved it to the .deprecated cs file

**Comment by vman** [comment]
Thanks. I was going to mark the ClearAvailablePageLayouts method as deprecated but thought it also makes sense as a method on its own.

I am also further modifying the AllowAllPageLayouts method to accept an optional parameter which will push the changes to subwebs. Will commit it soon.

**Comment by jansenbe** [comment]
good, ensure you refresh your branch with the update I just did.

**Comment by jansenbe** [comment]
We're trying to streamline the API and make it easier to use, so having 2 methods for the same function are not needed. AllowAllPageLayouts in in similar to SSOM and makes more sense.

**Pull request merged**
