### PR TITLE
Provisioning.PnPDeployer.Console

### PR DESCRIPTION
**Pull request by spplante**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes
| Related issues?  | None

#### What's in this Pull Request?

A small C# console application for easily deploying XML templates (or openXML ".pnp" packages) to on-premise or online sites. The console application uses a `sequences.xml` configuration file in order to orchestrate the different templates and their firing order, and it takes care of the `logging`, `tokenizing` (not the out-of-the-box tokens already available in PnP templates but tokens across static files anywhere across the client package), `authentication` and `command-line experience`. See the README.md file for a more detailed description of the solution.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Simon, looks like a really nice sample on the package handling. We will target getting this included in the September master merge happening this Friday.

**Comment by spplante** [comment]
Would be awesome :) Thanks Vesa!

**Comment by VesaJuvonen** [comment]
This looks really good would be pretty much ready to get migrated to samples gallery. Only thing I'd ask is to slightly modify the readme to include the standard information from our readme template as in to have sections on Applies to, Prerequisites, Solution and Version history. See https://github.com/OfficeDev/PnP/blob/master/readme-template.md or other samples as reference for the structure. You already have a great information in the readme on the purpose, but having those standard sections would be appreciated, so that it's aligned with other samples. So - if possible - you can add one more additional commit on this PR or re-submit with those changes and we'll get this one merged. If you can do that by EOD Thursday, we can still get this included in September release. 

Hopefully works for you.

**Comment by spplante** [comment]
No problem I will do this tonight!

**Comment by spplante** [comment]
All done! Let me know if there's anything else :)

**Comment by VesaJuvonen** [comment]
That was fast. Thx for that. Great work on this. I'll get it included and listed as new sample in the monthly communications. If there's any surprises with the final testing, I'll let you know, but all looks really good and extremely well documented... which is important, so that others will understand the value of your work. Great job.

**Comment by spplante** [comment]
Thanks Vesa! One small detail, I just noticed a copy/paste error in my readme.md file, under the prerequisites section, when listing the available nugget packages, I wrote "SharePoint PnP Core library for SharePoint 2013 (SharePointPnPCoreOnline)" with "2013" instead of "Online"...Since it's a minor detail in the readme, can you guys do a quick fix directly in the master branch (since I normally shouldn't be allowed to do anything in the master) or I would have do create a new branch etc? I know it's not much but it's bugging me haha

**Comment by VesaJuvonen** [comment]
Since we already did the master merge, would like to delay that update until Oct merge, since it's not really critical. Exact NuGet package really depends on your target environment, so it's debatable anyway. Hopefully delaying would be fine for you now, even thought that might bug you a bit.

**Comment by spplante** [comment]
Absolutely no problem!

**Pull request merged**
