### PR TITLE
Office365 API MVC Multi-tenant sample added and global refactoring

### PR DESCRIPTION
**Pull request by PaoloPia**
Guys,
I made a global refactoring of the project, isolating the Sample classes into Helper classes in a dedicated library. I shared that library both with WPF and a new ASP.NET MVC web application.
I added an ASP.NET MVC web application, which leverages OWIN and OpenId Connect with multi-tenancy, to show how to consume Office 365 API on behalf of the currently logged in web user.
Now, I think the Office 365 API Demo is almost complete.
Feedbacks and fixes :-) are more than welcome!

Paolo

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Paolo,

Thanks a lot for this contribution! 

Before we can accept your changes we would need to ask you to sign a collaboration agreement. Can you please fill in the sections highlighted in yellow, sign it and send a scanned version to Office365PnP_CA@microsoft.com.

**Comment by PaoloPia** [comment]
Bert, sorry for asking but: where can I find the file to fill and sign? I can't see it. Thanks.

**Comment by jansenbe** [comment]
My apologies Paolo, while editing my initial comment I've dropped the link to the agreement document. You can find this here: [collaboration agreement](https://github.com/OfficeDev/PnP/blob/dev/Microsoft%20Corporation%20Collaboration%20Agreement-Officedev%20Patterns%20%26%20Practices%20GetHub%20Project.docx)

**Comment by PaoloPia** [comment]
Document filled, signed and sent.
Thanks,
Paolo

**Comment by erwinvanhunen** [comment]
Thanks Paolo! I'll look into it and merge it today.

**Comment by erwinvanhunen** [comment]
Merged and thanks!

**Comment by PaoloPia** [comment]
Thanks buddy!

**Pull request merged**
