### PR TITLE
Added Azure AD - Web API - SharePoint Online integration using OAuth

### PR DESCRIPTION
**Pull request by RARomano**

### CODE REVIEW

**Comment by frankmarasco** [comment]
Hi RARomano, thank you for your contribution.  Can you please submit a pull request to the dev branch. Here the guidance on contributing back to PnP https://github.com/OfficeDev/PnP/wiki/contributing-to-Office-365-developer-patterns-and-practices

**Comment by frankmarasco** [comment]
closing this item please submit a pull request to the dev branch https://github.com/OfficeDev/PnP/wiki/contributing-to-Office-365-developer-patterns-and-practices

**Comment by RARomano** [comment]
Hi Frank,

Sorry about that. I'll submit it to the dev branch later this weekend.

Thank you!

Regards,
Rodrigo Romano

Sent from my iPhone

On 16/06/2015, at 10:18, Frank Marasco <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi RARomano, thank you for your contribution. Can you please submit a pull request to the dev branch. Here the guidance on contributing back to PnP https://github.com/OfficeDev/PnP/wiki/contributing-to-Office-365-developer-patterns-and-practices

-

**Comment by frankmarasco** [comment]
No worries my friend it happens to all of us :)

From: Rodrigo Romano
Reply-To: OfficeDev/PnP
Date: Thursday, June 18, 2015 at 8:18 AM
To: OfficeDev/PnP
Cc: Frank Marasco
Subject: Re: [PnP] Added Azure AD - Web API - SharePoint Online integration using OAuth (#935)

Hi Frank,

Sorry about that. I'll submit it to the dev branch later this weekend.

Thank you!

Regards,
Rodrigo Romano

Sent from my iPhone

On 16/06/2015, at 10:18, Frank Marasco <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hi RARomano, thank you for your contribution. Can you please submit a pull request to the dev branch. Here the guidance on contributing back to PnP https://github.com/OfficeDev/PnP/wiki/contributing-to-Office-365-developer-patterns-and-practices

-

**Pull request closed without merging**
