### PR TITLE
Checking in v1 of Governance.SiteUsageReport. 

### PR DESCRIPTION
**Pull request by SharePointRadi**
This is the initial commit. The code is complete and working for the example.

It required minor additions to OfficeDevPnP.Core to enhance the SiteEntity object and Tenant.GetAllSiteCollections

I will next prepare thorough documentation.

Radi A.

### CODE REVIEW

**Comment by jansenbe** [comment]
Nice work Radi, appreciated!

**Comment by jansenbe** [comment]
Hi Radi,
I'm not yet checking in this sample as it misses app.config: can you also checkin app.config (best to remove your appid, appsecret and other personal information).  Looking forward to the documentation updates :)

**Comment by SharePointRadi** [comment]
On to it now :)

**Comment by SharePointRadi** [comment]
I've now added the app.config file and enhanced readme.md. Ready for review again.

**Comment by jansenbe** [comment]
Perfect. Merged :)

**Comment by VesaJuvonen** [comment]
Thanks Radi, appreciated.

**Pull request merged**
