### PR TITLE
peoplepicker: allow to navigate on search result lists using arrows (…

### PR DESCRIPTION
**Pull request by konradsikorski**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | 

#### What's in this Pull Request?
NEW feature:
Now in the search results popup user must to click desired element by mouse. This update allow user to select element using up/down keys and press enter to select it.

### CODE REVIEW

**Comment by jansenbe** [comment]
Nice addition @konradsikorski . We'll test this and get it merged. Thx for your contribution

**Comment by VesaJuvonen** [comment]
Hi konradsikorski, just an update that we have not forgot you. We'll get this merged soon. One ask though: If you'd like to get credited with your actual name, would suggest to update profile in the GitHub, so that we can give you credits on the contribution.

**Comment by konradsikorski** [comment]
Great news, I have one more update to this control. I will send it soon :)
BTW I have updated my profile.

**Comment by jansenbe** [comment]
Hi Konrad,

I've merged your change, apologies for the delay but summer holidays delayed things. 

Question: I'm not able to get the select style to show in Chrome/IE...it's correctly applied and works (pressing enter selects the right user) but somehow the visual elements (background / border) are now showing up. Would be good if you could take a look at this...I'm not the CSS expert :-)

**Pull request merged**
