### PR TITLE
Provisioning.pn p deployer.console

### PR DESCRIPTION
**Pull request by spplante**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | yes |
| New sample? | no |
| Related issues? | none |
#### What's in this Pull Request?
- Added a configurable parameter that allows the `deployer` to ignore specific sub folders in order to speed up the "tokenizing" process. Useful for quickly deploying a project with large non-production-sub-folders on a development environment such as a NPM project that contains a large node_modules sub folder for instance.
- Updated the FieldsExtensibilityProvider with an automatic attributes validator, making it a base template for future extensibility providers.
- Fixed a bug related to the global tokens stored in the app.config file of the console application's project. 
- Fixed a bug with the tokenizing try to tokenize non-text files such as images, videos etc...That would cause the deployment of corrupted files since the tokenizer was saving back those files into a corrupted format. Fixed the issue by only saving back the files that needed to be saved (File that actually had tokens inside them).
- Modified the client tokens XSD in order to provide a more consistent XML format.
- Removed the build events within the console application's project
- Updated the readme.md to reflect the changes

### CODE REVIEW

**Comment by spplante** [comment]
Hi Vesa,

I still have one quick fix I just noticed, is it too late for checking-in some changes in this pull request or I would be better opening a new pull request? Thanks!

**Comment by VesaJuvonen** [comment]
Feel free to push things in. Have not yet processed or started with this one.

**Comment by spplante** [comment]
All done. Thanks!

**Comment by VesaJuvonen** [comment]
thx Simon, all good.

**Comment by VesaJuvonen** [comment]
thx Simon

**Pull request merged**
