### PR TITLE
SharePoint JSOM and REST

### PR DESCRIPTION
**Pull request by Anil-Lakhagoudar**
This solution implements the JSOM and REST Api for retrieving the list
items more than 5000 items in batch.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Anil,
this looks really good and thx for your contribution. We do not however accept submissions directly to the master branch. All new PRs should be submitted to dev branch from where they are then merged to master during monthly master merge. 

We also do require that all samples are using same readme.md template from consistency perspective, so that one should be updated accordingly to include the basic structure. You can find the readme-template.md from the root of the repo or you can have a look reference from other samples. 

With these updates we should be then good.

**Comment by Anil-Lakhagoudar** [comment]
Hi @VesaJuvonen , i apologize for the mistake, i will update the readme.md according to the template. 
please let me know should i need to merge this to Dev branch now or i can work on this branch till it will merged to Master branch.

**Comment by Anil-Lakhagoudar** [comment]
Hi @VesaJuvonen 
I have updated the Readme.md file. let me know is that aligned with the structure.

**Comment by Anil-Lakhagoudar** [comment]
Hi @VesaJuvonen  may i know when this PR will be evaluated.

**Comment by VesaJuvonen** [comment]
Takes usually from few days to a week. Depends on the availability of the Core team members, but we try to work on these as fast as possible. Anyway by the time of November master merge / November release, so that you'll get included in the release notes.

**Comment by Anil-Lakhagoudar** [comment]
Thank you @VesaJuvonen for your quick response, Actually this is my second contribution for OfficeDev PnP , first one same functionality done in CSOM and this time i have implemented same functionality in JSOM and REST API.  Just wanted know the feedback about this solution so that it would help for my technical aspect.

**Comment by Anil-Lakhagoudar** [comment]
Hi Team,

when this PR will be evaluated.

Thanks,
Anil

**Comment by VesaJuvonen** [comment]
Hi Anil,
readme looks now good, but the PR is targeted to the master branch still like pointed in the original comment, so we can't process this. Would suggest to close this one and then submitting the PR to dev branch. We do monthly releases with the master branch with wider communications to manage the changes under the PnP.

**Comment by Anil-Lakhagoudar** [comment]
Hi @VesaJuvonen i have created another PR https://github.com/OfficeDev/PnP/pull/1202
as this request is targeting to Master branch.
hence closing this PR.

**Pull request closed without merging**
