### PR TITLE
Office 365 AddIn with Groups Authorization Sample

### PR DESCRIPTION
**Pull request by levalencia**
Office 365 AddIn with Groups Authorization Sample

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thanks Luis for this. There's two asks we would however have related on this.

- You will need to sign the electronic contribution agreement, which has been sent to your email or you can access that using https://cla.microsoft.com
- Second request relates on the naming of the sample. We do not actually use terminology of add-in related on the Office 365 API based solutions. That's only for SharePoint and Office. Better prefix for this one would be AzureAD so that it's grouped under similar samples (one exists already under samples before this one as well). This will help to categorize samples accordingly.

I'm sorry for the inconvenience related on the name change and we certainly will work on the guidance related on the right naming of the samples.

**Comment by levalencia** [comment]
ok fixed, do I need to create another pull request?

**Comment by jansenbe** [comment]
If you've fixed code in your Office365AddinWithGroupsAuthorization branch it will be automatically picked up, no need to issue a new PR. In reality a PR is a compare between your branch and the PnP dev branch at the moment it's being processed.

**Comment by jansenbe** [comment]
Thanks for signing the CLA Luis. Will have a look at the PR and process it

**Pull request merged**
