### PR TITLE
taxonomypicker.js updates

### PR DESCRIPTION
**Pull request by miket9884**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | Yes
| New sample?      | no

#### What's in this Pull Request?
- replaced $ with jQuery to avoid conflicts with SharePoint using '$'
- added support for retrieving term set by name (instead of only via guid)
- included custom properties when retrieving termsets
- added callback when terms are loaded
- fixed jQuery.taxpicker and picker index references so that the taxpicker control can be referenced via external code.

### CODE REVIEW

**Comment by miket9884** [comment]
closed this request, found an issue and want to fix it before this is merged.

**Comment by miket9884** [comment]
reopening... the issue that I thought we had was actually something else entirely so no changes were made beyond the original pull request.

**Comment by VesaJuvonen** [comment]
thx Michael, we'll have a look on this. Target is to get this to included for the June release.

**Comment by VesaJuvonen** [comment]
thx Michael, looks good. Getting merged for June release.

**Pull request merged**
