### PR TITLE
Created a simple console app to make testing site provisioning easier…

### PR DESCRIPTION
**Pull request by SharePointRadi**
… and to illustrate "getting started" with site provisioning.

It really is just to quickly demonstrate it to new people. I will also use it for a "getting started" blog post.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Radi,
this seems to be pretty much story as following which was released with the April master merge - https://github.com/OfficeDev/PnP/tree/master/Scenarios/Provisioning.Framework.Console

Also since this is having reference to Core compoment, it should not be under Samples since those are fully isolated. Scenarios are for showing how Core component work, which is why the April sample is under that folder.

If https://github.com/OfficeDev/PnP/tree/master/Scenarios/Provisioning.Framework.Console would require any updates from your perspective, let's rather update that one, than having multiple pretty similar samples in the library.

Sounds good?

**Comment by SharePointRadi** [comment]
You're right, I have somehow missed Provisioning.Framework.Console. I will go over it and see if there is something work adding.

**Comment by SharePointRadi** [comment]
Hey @jansenbe, can I modify your console example?
I want to add the ability to type in your URL's and to see the progress bar.

**Comment by VesaJuvonen** [comment]
Please do update existing ones rather than create new. This one is effort from the whole PnP engine crew and you can certainly update that bases on need.

Best regards,
Vesa Juvonen

Senior Program Manager
Office 365 Customer Adoption Team
Microsoft Certified Solutions Master: SharePoint
Ready to use Office 365 App patterns and practices from http://aka.ms/officedevpnp

Sent from mobile phone by Vesa, so excuse the Thumblish and Finglish nuances.
________________________________

**Comment by SharePointRadi** [comment]
I've merged the stuff into Provisioning.Framework.Console. It now has some color and asks users for URLs and credentials, and displays messages from the trace listener. The most important stuff is a few null checks and try/catch;s in the core code. Please review.

**Comment by VesaJuvonen** [comment]
Hi Radi,
Seems that we are still lacking your CLA signature. Could you check your email which you used for the GitHub registration. There should be electronic signing form with DocuSign, which would have to be signed before we can get this processed. You are definitely fine for this, but it's just matter or clearing this for the process and signature is one time thing.

**Comment by SharePointRadi** [comment]
Done :)

**Comment by jansenbe** [comment]
Thanks Radi. Will have a look at this and merge it

**Comment by jansenbe** [comment]
Hi Radi,

Let's work offlline on this PR: problem is that it's a mix of things which makes it hard to merge. Feel free to reach out to me so I can help: in the future it's best to have individual changes in their own branches and then create a PR per branch.

**Comment by jansenbe** [comment]
closed per private mail discussion

**Pull request closed without merging**
