### PR TITLE
Enable template to include features which have been deactivated from …

### PR DESCRIPTION
**Pull request by nickcox**
…base template.

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Thank you for your contribution! It's an interesting PR I think, and I will check it out the coming days.

**Comment by jansenbe** [comment]
PR will require manual porting to new PnP-Sites-Core repo + merging with current code

**Comment by jansenbe** [comment]
Hi Nick,

Thanks for contributing this PR! 

This PR has been open for a long time due to the fact that we've been restructuring the PnP repositories. Today the provisioning engine updates happen in the PnP-Sites-Core library and a lot of changes have been implemented over the last months. 

Therefore it's very hard for us to merge this PR as is...we would like to ask you to resubmit this PR (if still relevant) as a new PR in the PnP-Sites-Repo. We apologize for the extra efforts this is resulting into.

This also means that we're going to close this PR in the PnP repo.

Best regards,
The PnP Core team

**Comment by nickcox** [comment]
Thanks, Bert.

How should I stop this sort of thing from happening again? Is there some sort of roadmap where contributors can find out about upcoming major restructures?

**Comment by jansenbe** [comment]
The repo split is the only major restructuring we did over the last 1,5 years...and no new major restructuring is planned. It's unfortunate that it collides with your PR submission, apologies for that.

**Pull request closed without merging**
