### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by braegelno5**
now also with enhancements to the readme.md

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Torsten,

Thanks for this PR. We've just discussed this one in our weekly core team meeting and have mixed feelings about implementing it as it's adding a lot of code to our base RER sample in PnP. The way how you've solved the problem is fine, but maybe we should use a different approach to explain this to the PnP users: ideas we have are adding this approach (and the code snippets) as documentation or alternatively create a second RER sample. We'll need to spent some more time on this and will come back to you with our advise.

**Comment by VesaJuvonen** [comment]
Hi Torsten,
this is great idea and we absolutely will use some of the code which you have provided to explain this option in documentation. We can't however accept this as such, since this is one of the fundamental simplistic samples referenced also in MSDN and other sources. Your implementation is fine and good, but it adds too much complexity on the sample.

We will extract the code from the submission and update the documentation accordingly as additional option or enhancement which could be applied. You will absolutely get credits from this work in our March release.

**Comment by VesaJuvonen** [comment]
and btw. let's keep this still open, until the documentation is updated.

**Comment by jansenbe** [comment]
Documentation has been updated and we've credited you for the work Torsten. Thanks!

**Pull request closed without merging**
