### PR TITLE
js-sites-core ported from github.com/olemp/js-sites-core

### PR DESCRIPTION
**Pull request by olemp**
### Introduction
This is js-sites-core ported from github.com/olemp/js-sites-core and restructured to fit the current model of the Core.JavaScript library (AMD/Require.js).

I've removed quite a bit from the original js-sites-core to keep it simple in the beginning. Some of the logging etc (starting simple for now).
The Object Handler for Pages was also not ready.

### Structure
The structure is
pnp => sharepoint => provisioning

### SharePoint/Util
Some Util methods was needed, and they're added to SharePoint/Util.ts.

##### encodePropertyKey
Encodes property bag entries. Needed by Property Bag Entries to set properties as indexed.

##### replaceUrlTokens
Replaces tokens like {site} and {sitecollection}. Uses _spPageContextInfo.

Also want to support
* {webpartgallery}
* {siteassets}
* {resources} (Which can be specifed by the user in e.g. Web Property Bag)

##### getNodeFromCollectionByTitle
Used in Navigation to get a Node with from a Node Collection with the specified title.

##### getRelativeUrl
Transform a absolute URL to a relative. Used in Composed Look since it's needs the ServerRelativeUrl.
Could perhaps be renamed to getServerRelativeUrl?

**NB** We need to mock up document.location and _spPageContextInfo to create tests for these.

### Core 
Under Provisioning, we have the *Core* module/class.

Core has one public function:
* applyTemplate()

### applyTemplate()
You would simply call it like this with a URL to your JSON template. A ES6 promise is returned.

The following tokens can be replaced for you:
* {sitecollection}
* {site}
* 

An example URL would be *{sitecollection}/SiteAssets/templates/taskroom.txt*

```javascript
pnp.sharepoint.provisioning.core.applyTemplate([URL]).then(function(result) {  })
```

This is a simple example of a template:

```json
{
  "PropertyBagEntries": [
    {
      "Key": "Template",
      "Value": "SimpleTaskRoom",
      "Indexed": true
    }
  ],
  "Lists": [
    {
      "Title": "Tasks",
      "Url": "Lists/Tasks",
      "TemplateType": 171
    },
    {
      "Title": "Documents",
      "Url": "Documents",
      "TemplateType": 101
    }
  ],
  "Files": [
    {
      "Dest": "SitePages/Home.aspx",
      "Overwrite": true,
      "Src": "{sitecollection}/SiteAssets/Home.txt",
      "RemoveExistingWebParts": true,
      "WebParts": [
        {
          "Title": "SiteFeed",
          "Zone": "Main",
          "Order": 0,
          "Contents": {
            "FileUrl": "{sitecollection}/_catalogs/wp/SiteFeed.dwp"
          }
        }
      ]
    }
  ],
  "Navigation": {
    "QuickLaunch": [
      {
        "Url": "",
        "Title": "Home"
      },
      {
        "Url": "Lists/Tasks/AllItems.aspx",
        "Title": "Tasks"
      },
      {
        "Url": "Documents/Forms/AllItems.aspx",
        "Title": "Documents"
      }
    ]
  },
  "ComposedLook": {
    "ColorPaletteUrl": "{sitecollection}/_catalogs/theme/15/palette008.spcolor",
    "FontSchemeUrl": "{sitecollection}/_catalogs/theme/15/SharePointPersonality.spfont"
  }
}
```

### applyTemplate() options (not in this Pull Request)
In the original JS Sites Core, applyTemplate() takes a second argument *options*, but I chose to not bring this
into this pull request, mostly because there should be a better place to handle provisioning config.

The options are
* WaitMessageOptions
* LoggingOptions

##### WaitMessageOptions
* Header
    * The Header on the WaitMessage ([SP.UI.ModalDialog.showWaitScreenWithNoClose](https://msdn.microsoft.com/en-us/library/office/ff408140(v=office.14).aspx))
* Content
    * The Content on the WaitMessage ([SP.UI.ModalDialog.showWaitScreenWithNoClose](https://msdn.microsoft.com/en-us/library/office/ff408140(v=office.14).aspx))
* ShowProgress
    * Should a Progress Bar be present in the WaitMessage?
* ProgressOverrides
    * Custom messages under the Progress Bar?
    * Defaults are Lists, Pages, Files etc.

capture 2016-03-06 at 15 10 08

##### LoggingOptions
* On
   * Should there be logging in console?
* LoggingFolder
    * Should a summary be saved as a file to e.g. Site Assets, or a custom library with a custom content type allowing for more data on the log file

**NB!** In Puzzlepart, we're using js-sites-core for several customers, and the LoggingFolder concept is very neat! If provisioning fails for the customer, they can just send us the .txt file, or we if we have a user in their tenant, we can have alerts on the list!

capture 2016-03-06 at 15 12 12

### Schema
Have a look at the schema here (not yet ported):
https://github.com/Puzzlepart/js-sites-core/blob/master/dist/schema.md

### Object Handlers
The Object Handlers are pretty solid now, but *Pages* and *Lists* can be improved.

### Logging
The output from calling *applyTemplate()* with this file would be:
```txt
Sat Mar 05 2016 14:21:44 GMT+0100 (W. Europe Standard Time) 		 [Provisioning] 		 [Information] 		 Code execution scope started
Logger.js:31 Sat Mar 05 2016 14:21:44 GMT+0100 (W. Europe Standard Time) 		 [PropertyBagEntries] 		 [Information] 		 Code execution scope started
Logger.js:31 Sat Mar 05 2016 14:21:44 GMT+0100 (W. Europe Standard Time) 		 [PropertyBagEntries] 		 [Information] 		 Code execution scope ended
Logger.js:31 Sat Mar 05 2016 14:21:44 GMT+0100 (W. Europe Standard Time) 		 [Lists] 		 [Information] 		 Code execution scope started
Logger.js:31 Sat Mar 05 2016 14:21:46 GMT+0100 (W. Europe Standard Time) 		 [Lists] 		 [Information] 		 Code execution scope ended
Logger.js:31 Sat Mar 05 2016 14:21:46 GMT+0100 (W. Europe Standard Time) 		 [Files] 		 [Information] 		 Code execution scope started
Logger.js:31 Sat Mar 05 2016 14:21:47 GMT+0100 (W. Europe Standard Time) 		 [Files] 		 [Information] 		 Code execution scope ended
Logger.js:31 Sat Mar 05 2016 14:21:47 GMT+0100 (W. Europe Standard Time) 		 [Navigation] 		 [Information] 		 Code execution scope started
Logger.js:31 Sat Mar 05 2016 14:21:48 GMT+0100 (W. Europe Standard Time) 		 [Navigation] 		 [Information] 		 Code execution scope ended
Logger.js:31 Sat Mar 05 2016 14:21:48 GMT+0100 (W. Europe Standard Time) 		 [ComposedLook] 		 [Information] 		 Code execution scope started
Logger.js:31 Sat Mar 05 2016 14:21:59 GMT+0100 (W. Europe Standard Time) 		 [ComposedLook] 		 [Information] 		 Code execution scope ended
Logger.js:31 Sat Mar 05 2016 14:21:59 GMT+0100 (W. Europe Standard Time) 		 [Provisioning] 		 [Information] 		 Code execution scope ended
```

This should be recognizable for those who've used the PnP Sites Core framework (which I have used a lot).

### CODE REVIEW

**Comment by olemp** [comment]
Here's an example of usage: https://github.com/olemp/provisioning-js-sites-core

Looking forward to your input!

**Comment by patrick-rodgers** [comment]
Hi Ole, I took a look at this over the weekend - looks good. Obviously this is a pretty big PR. Because we have had a lot of people submit things very quickly there are some conflicts. I merged several this weekend but was wondering if you could merge your code with latest and update the PR? Because there are so many files I want to avoid braking your work.

**Comment by olemp** [comment]
@patrick-rodgers: No worries! I will do as soon as I get time!

**Comment by olemp** [comment]
@patrick-rodgers New PR here: https://github.com/OfficeDev/PnP/pull/1346

Closing this one then.

**Pull request closed without merging**
