### PR TITLE
Taxonomypicker - support for term suggestions based on containing

### PR DESCRIPTION
**Pull request by HenrikGustafsson**
Added support for something that people have been asking me for when using SharePoints own taxonomypicker - being able to find things on terms not only starting by, but also containing. The problem is that users don't always know exactly the term they are looking for and sometimes have a  hard time finding the correct term. This can result in "duplicate" terms because users create new ones instead of using the existing ones.
Thanks @pbjorklund for fixing my git issues!

fuzzy-highligt
standard

### CODE REVIEW

**Comment by HenrikGustafsson** [comment]
Hi @jansenbe - I already signed a cla once but maybe I need to sign a new one since I am in new company since I signed the last one? Didn't receive any form to sign yet in any case...

**Comment by VesaJuvonen** [comment]
Hi Henrik,
you should have received an email with electronic form to sign for. Company change does impact on this one. You can also access the CLA signing just by using following url: https://cla.microsoft.com. When the form has been submitted, status of this PR will change automatically.

**Comment by HenrikGustafsson** [comment]
Thanks Vesa, went with the direct link and signed it.

**Comment by jansenbe** [comment]
Excellent. We'll have a look at this PR.

**Comment by jansenbe** [comment]
Nice work :-) Merged.

**Pull request merged**
