### PR TITLE
Update AddSPOField.md

### PR DESCRIPTION
**Pull request by etiennebailly**
I proposed a second example (Multiple Choice)
My first and very modest contribution...

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Etienne, thanks for this contribution. All contributions are valuable, also the small ones :)

I've noticed that this PR has been created against our master branch which is a problem since we're accepting PR's on that branch. Can you close this PR and create a new one and this time compare against our DEV branch. Thanks :)

**Comment by etiennebailly** [comment]
Hello, of course i will try to do that ☺
That’s why i chosed to try with a very very small contribution because i’m quite noob yet with github

So i try to make my PR on the DEV branch ☺

De : Bert Jansen [mailto:notifications@github.com]
Envoyé : vendredi 19 juin 2015 18:00
À : OfficeDev/PnP
Cc : Etienne Bailly
Objet : Re: [PnP] Update AddSPOField.md (#967)


Hi Etienne, thanks for this contribution. All contributions are valuable, also the small ones :)

I've noticed that this PR has been created against our master branch which is a problem since we're accepting PR's on that branch. Can you close this PR and create a new one and this time compare against our DEV branch. Thanks :)

**Comment by etiennebailly** [comment]
wrong place, i'll try again on dev branch

**Comment by erwinvanhunen** [comment]
Hi Etienne, another remark: the documentation for the cmdlets are autogenerated based upon the source code. 

This means that the moment we do the master merge this documentation will be overwritten by the generated version. We however do appreciate your efforts very much, but if you can please add the additional example to the file that is the source for the documentation. See https://github.com/OfficeDev/PnP/blob/master/Solutions/PowerShell.Commands/Commands/Fields/AddField.cs#L12 to see how we specify the examples in the source code. If you add your example there, (just add another [CmdletExample] block) it will be part of the documentation generation step.

**Pull request closed without merging**
