### PR TITLE
SiteExists method language agnostic implementation

### PR DESCRIPTION
**Pull request by nanddeepn**
Current implementation of SiteExists method works on sites created in EN language as the ex.Message check is performed against "Unable to access site" and "Cannot get site". Although non existing site throws error "File Not Found."
Removed the language specific site existence check. With new implementation:
1. Check if site exists
2. Check if site is recycled.
3. Return false, if 1 and 2 not satisfied.

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Nanddeep, thanks for the proposed change.

We're not going to take this change as we're still looking into a better solution (see #392). The idea is to use server error versions or look at making the string translatable via resource files

**Comment by nanddeepn** [comment]
Thank you for the update @jansenbe 

I had a look at the OOB Resources files in 15 hive on my farm to see if the errors are being picked from there, but I was wrong.
Please let me know, if I can contribute any part in your research because I being mostly working with non English sites development - I had to always look out for the language agnostic solutions. Hope you understand my pain :)

**Comment by jansenbe** [comment]
I certainly do and we're working on it. Are you saying that you don't see these error messages in the 15 resource files?

**Comment by nanddeepn** [comment]
Hello Bert,
Yes, I did not see the error message in 15 resource files. I will recheck if I have overlooked anything and confirm you by couple of hours.

**Comment by nanddeepn** [comment]
Hello Bert,
I did not find the error messages in 15 resources files.

Found a few mentioned below, but no luck
Unable to access site
Cannot get site

**Pull request closed without merging**
