### PR TITLE
Created guidance on taking O365+AzureAD project from local dev => Azure website

### PR DESCRIPTION
**Pull request by andrewconnell**
Created guidance doc with images how to configure an Office 365 API project from a development experience that uses the http://localhost for testing to be deployed to an Azure Website, including the changes required to the project as well as the Azure AD application.

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Andrew,

Think it would be better to not upload the images to the guidance folder. For all other MD files the images are uploaded to github storage. We use a tool named MarkDownPad (http://www.markdownpad.com/) that has a built in function to make adding images easy. It will upload to internet storage (http://i.imgur.com) but once the MD file is stored on github it will be referenced via https://camo.githubusercontent.com.

**Comment by andrewconnell** [comment]
You really don't want images as part of the source? Doesn't that defeat the purpose of keeping everything together in a release or update... won't links break for offline sharing when you aren't connected? Asking because this is a bit surprising to me from other OSS projects I've contributed to. I was actually going to base64 them right into the doc at first :)

OK... I'm not sure if this is a specific request for me to post the images => Imgur & update the MD or if it was more of a discussion... can you clarify & if there's an action item I'll get it sorted.

**Comment by jansenbe** [comment]
Links will indeed break when offline, but how often is this content consumed when offline? All MD files in PnP have their images outside of the repository. There's limited value in having them with the MD files, but we'll soon end with a large folder of images with a few md files in between and will increase the size of the repo quickly. I'm not saying that's all bad, but just different that we've been doing so far. When using MarkDownPad the whole image handling is taken care of automatically, no need to perform any manual upload or updates. When a new version of an image is added to an MD file you'll automatically get a new image URL and as such the old MD version still shows the old images. 

We should agree on a convention, so asking other team members for feedback.
@VesaJuvonen, @frankmarasco , @erwinvanhunen: what do you think?

**Comment by andrewconnell** [comment]
OK... I'll wait to see what the PnP powers that be say :). BTW, don't assume all use MarkdownPad... many use Atom / Sublime. I don't think that's necessary factor in this though. Personally I can't use MarkdownPad as it's a Windows app & I'm on OSX.

**Comment by jansenbe** [comment]
Definitely valid point about OSX. I also only now see you're storing the images in a sub folder. We'll discuss this in our weekly core team meeting...following options are possible, but feel free to provide your insight:
-  MD file in guidance folder + images in "images" folder (pro: offline, better compatibility with other MD editors / con: size increase of repo, different than all other MD files)
-  MD file in guidance folder + images in githubusercontent  (pro: no repo size impact, easy with most used MD editor, similar to all existing MD files / con: editing using other clients)
-  Use separate PnP Guidance repository:
  -  Pro: Only one branch (master)...dev branch for guidance documentation is not really needed
  -  Pro: Images can be included in repo without impacting PnP repo size
  -  Pro: Easier to setup a proper guidance information architecture as it's all about guidance
  -  Con: second repository might be less discoverable (but we can link from PnP repo/wiki)

All: Feel free to propose alternatives are let us know your preference

**Comment by andrewconnell** [comment]
So first, I'd suggest we move this to an issue that we can reference & others can track... then if you really want input from the community, mention it in the next community call and point them to the issue. 

*Now for my soapbox... before I start, all my opinions are based on other private & public projects I work on in GitHub... none of the stuff here is original thought. My motivation in this discussion is to push PnP to follow what I believe the greater community is doing and not come up with another "Microsoft" solution.*

IMHO, I don't think the majority of the people out there are using MD editors. They are nice, but the rise of more streamlined tools, esp those within the OSS community, have folks using the editor they choose. With MD files being so ingrained in projects on GH, most are doing the editing of those files within their projects. Editors like Visual Studio & WebStorm already have plugins... tools like SubText have extensions as well. I personally think it's a small subset of the population that is buying MD editing tools.

As for **my opinion** on how this should work, I think **the images should reside within the same repo**. The pattern I proposed was to have a `/Images` folder and then name the image the same as the guidance article with a `-##.png` suffix so you know what images go with what article. The other option is to have a subfolder within `/Images` for each article that needed it. If you update an image in an external source, it might be tied to a specific version release and part of the same PR by a contributor. Having them in external resources breaks this convention. Personally I'm not concerned about the size... we are talking about PNG's... not PSD's or AutoCad files. This is how the OfficeDev/TrainingContent & virtually all other repos within OfficeDev do it that provide some sort of guidance. The only exception to what isn't stored in GitHub are videos... ala really big files.

As for "should guidance be in/out of the PnP"... I don't think there will be a discoverability problem... that can be solved on [dev.office.com](http://dev.office.com) and in the root README.md in the repo... 

With that being said, I think it makes perfect sense to leave it where it is. Other repos have `/docs` or `/faq` folders for guidance OR they use the wiki for the repo (this was originally my rec to @VesaJuvonen in an offline email thread when this was being debated). Wiki's can be cloned locally and support histories... but the downside is you don't get the merging & PR capabilities that you get with the bigger repo. I would leave the wiki for official PnP documentation that should only be authored / owned by the repo owners... not contributions by the community.

**Comment by pbjorklund** [comment]
When I converted some docs I just wrote the MD and uploaded the images to imgur (since that was the agreed upon approach for images). But thats because I only read formatted MD on github, otherwise I do all reading/writing in vim or vs.

Seeing as the images are tightly coupled with the readme and the readme is coupled to the current version of the code then yes, the images should be versioned together with the repo so that you can check out the correct version of both the readme and the code.

My main gripe is with the size of the repo in general. Why not just break things out to repos and link them together with submodules? Then I can choose what submodules to actually init depending on what I want to see.

**Comment by frankmarasco** [comment]
I think we should probably look at splitting things out. There is another discussion about splitting core out perhaps maybe we should do the same with the guidance. .https://github.com/OfficeDev/PnP/issues/319

**Comment by VesaJuvonen** [comment]
I'd be tempted to start with following changes and then move from there. Comments and feedback is more than welcome and encouraged before we actually do this. We will talk about this also during the January community call on Tuesday 13th of Jan (https://github.com/OfficeDev/PnP/wiki/Community-call).

Split current PnP to three different repo's: 
- Core to own PnP-Core repo
- Guidance to own PnP-Guidance or PnP-Articles repo
- Samples, scenarios and solutions still to own repo - we can continue splitting these at some point as needed

We are working on MSDN update process directly from the guidance documents / articles and above split of the articles will be beneficial for that as well.

With assets, including images, we should follow the example from the Azure. They have own sub folder for media in article repo. See example from here - https://github.com/Azure/azure-content. Right now this is wild wild west from the Office PnP side, which is as expected, since we have concentrated more on getting things moving than controlling things too detailed. We will have to now start controlling this is more detailed process due the growth of the program.

Comments?

**Comment by VesaJuvonen** [comment]
And yes... maybe a RP comments is not the best location for this chat, but as long as we have ongoing discussion... :-)

**Comment by jansenbe** [comment]
Definitely like the idea to split off the guidance part and follow the Azure convention. 

Regarding splitting core into separate repo we need to also consider the scenarios and solutions that use core. Today these all have the core project embedded, so if we split this we either need to stop doing so or we need to clearly explain that people need to pull down both repo's and keep both up to date. Today we sometimes get feedback that getting started with PnP is hard...moving to different code repository which are depending on each other will make this worse. 

If we take out all the guidance related content (folders Documentation, Guidance) we'll decrease the PnP repo size with 70 MB (I personally don't mind that the repo is a not small: you only download the full repo once and then it's just deltas). We can then still leave all the code together in one repo. This way we'll not disrupt the current user base. If we really want to split the code out we need to communicate well upfront as people might have stuff ready in their PnP fork...but can't commit it anymore due to our changes.

**Comment by erwinvanhunen** [comment]
I agree with Bert, I don't mind it either that the repo is not small. It used to be more of an issue before the NuGet package was available, as people had to download the whole repo, build the core project and use the resulting assemblies. I also agree with Bert that splitting up the project into several repos might actually cause a fair share of confusion among people that are new to the project.

A possible scenario towards a (future) split up could be that we say that -every- solution, sample, scenario should make use of the NuGet package instead. That way there is no dependency between the projects. 

I haven't looked into yet though how that would affect the PowerShell cmdlet solution, as I have a build config for both V15 and V16 there.

**Comment by PaoloPia** [comment]
Even if my contribution to the project is small, I would like to give my feedback about this topic, which is fundamental in my opinion. And personally I agree with Erwin and Bert. I would keep a unique repository, because splitting code across multiple repositories would make the things more complex and could make it difficult for existing and new contributors to contribute comfortably.

Nowdays download size shouldn't be a real issue.

Thanks,
Paolo

**Comment by VesaJuvonen** [comment]
Approving this one and we will be working on getting the guidance to its own repo for easier publishing process to other target systems, so that we can handle community contributions to articles and update reference locations in future. 

We will make the necessary re-organization for images when this material moving over.

**Pull request merged**
