### PR TITLE
Initial structure for SharePoint. Provisioning will be merged from js-sites-core

### PR DESCRIPTION
**Pull request by olemp**
Initial structure for SharePoint. Provisioning will be merged from js-sites-core (https://github.com/Puzzlepart/js-sites-core).

Just checking if basic structure is fine first.

Also added typings for SharePoint to typings.json.

### CODE REVIEW

**Comment by artokai** [comment]
Hello,

Could you switch from tsd.json to typings.json since TSD is deprecated and the project is already using typings.json?

Just run "`typings install --save --ambient sharepoint`" in the command prompt and you're all set.

**Comment by olemp** [comment]
@artokai Sure thing.

**Comment by olemp** [comment]
@artokai https://github.com/olemp/PnP/commit/7ff084c9562b14721e23e347c5a86fbccf1449a6

Looks good?

**Comment by artokai** [comment]
Thanks!

**Pull request merged**
