### PR TITLE
Addition of template defined Site Policies

### PR DESCRIPTION
**Pull request by wictorwilen**
Templates now allows to use the site policy specified in the
provisioning template to be used in favor of the one specified by the
classification.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Wictor. We'll add notes to Nov readme around the change needed for the request list for this one, since existing deployments will otherwise be impacted.

**Comment by wictorwilen** [comment]
Thanks Vesa! Overall we need to work out a better documentation for that sample since the default readme is now humongous

**Comment by VesaJuvonen** [comment]
Absolutely agree on that. We are also just about to release new packaged version of similar solution under the PnP Partner Pack, which partly overlaps with this one. Whole point of the PnP Partner Pack is that it's more packaged and polished with proper documentation on setting it up to any tenant... slightly overlapping with this sample, but idea is that those are isolated. See dev branch under https://github.com/OfficeDev/PnP-partner-pack

**Comment by wictorwilen** [comment]
I'd say that this is very unfortunate and not a good move for PnP, not for these solutions or the whole project in general. Now you're competing with yourself with no clear path forward. Just pushing out new projects, solutions, samples etc does no good, they need to be maintained...

**Comment by VesaJuvonen** [comment]
Yes and no. This is now the first time we have clear plan and are starting to move to that direction. Whole point is to ensure that we have reusable solution which can be deployed easily cross any tenant. In the end PnP repo has huge amount of random samples, but it's really hard to find the most meaningful ones. PnP Partner Pack is the solution for this and whole point is that anyone can easily adapt the models.

We have not yet openly communicated on this, except in the monthly calls, but whole point is to ensure that we have proper fine tuned and polished solution, which has needed scripts and documentation for easy consumption... which has been lacking. So - this is first step towards more structural model. Finally.

**Pull request merged**
