### PR TITLE
3 Governance Solutions - Change Site Collection Ownership, External S…

### PR DESCRIPTION
**Pull request by chandrasekarngit**
…haring Settings, Add-In Security

### CODE REVIEW

**Comment by jansenbe** [comment]
Thx Chandrasekar , excellent solution!

**Comment by jansenbe** [comment]
I've merged your work but somehow github is not marking the PR as merged...will close manually

**Comment by VesaJuvonen** [comment]
Hi @chandrasekarngit , it seems that in #1339 pull request we still had Governance.ExternalSharing/Governance.ExternalSharing solution included in this, but that was no longer in this one. Not sure if this was intentional, so wanted to double check. If that's still meant to be shared, please submit a new pull request on that one, so that we can get that shared with May release.

**Comment by jansenbe** [comment]
Re-trying merge...somehow part of the PR was not pulled down...

**Comment by jansenbe** [comment]
Merged again and now successful...previously I've taken the wrong branch, my mistake

**Pull request merged**
