### PR TITLE
Adding Outlook Notifications REST API with ASP.NET Web API sample

### PR DESCRIPTION
**Pull request by simonjaeger**
This is a sample of an ASP.NET Web API project validating and responding to Outlook Notifications - created with the Outlook Notifications REST API.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx Simon, we'll have a look on this during upcoming days. Looks good as a first glance.

**Comment by jansenbe** [comment]
Hi Simon,

Thanks for your submission! I've inspected the code and things are fine if you only focus on the webAPI part. However if someone wants to try this they'll already need to fully understand the notifications model: would it be possible to add a simple UI that the user can use to register the notification. Once this is there the sample can be 'tested' by simply registering the app in Azure AD.

I'm happy to add these changes if you don't have time, but would be great if you could do this as well :-)

Regards,
Bert

**Comment by simonjaeger** [comment]
Bert,

Thank you for your inspection! I'll get to it and add the UI part once I find some spare time. 

Cheers,
-Simon

**Comment by jansenbe** [comment]
Excellent! Let me know if you need my help.

**Comment by simonjaeger** [comment]
I've added UI now for registering notification subscriptions to the sample! Thanks for the feedback!

**Comment by jansenbe** [comment]
Super :) I'll have a look at this PR in the coming days.

**Comment by VesaJuvonen** [comment]
Thx Simon, looks really valuable and helps people to understand how this can be done in practice. Looks absolutely potential candidate as a demo in the February monthly community call.

**Comment by pschaeflein** [comment]
Nice sample Simon!

There is one key concept that is missing, IMO. The notification payload has only the Id of the item causing the notification. Typically, the consumer of the notification would need to inspect the item, which requires a call back to the graph, which requires a token.

I would be happy to extend the sample to include the token acquisition based on a persisted refresh token. Is that already in progress? Or already in a different part of PnP? (That last one may be a question for @jansenbe or @VesaJuvonen ...)

**Comment by simonjaeger** [comment]
Thanks Paul! I took the time to implement this... *phew*. I appreciate the feedback.

**Comment by jansenbe** [comment]
Thanks guys. I'll get the sample included in PnP in the coming days! Keep up the good work :-)

**Comment by jansenbe** [comment]
Merged. Not sure why it's not automatically listed as merged...so I'll close the PR manually. 

Great work Simon!

**Comment by simonjaeger** [comment]
Thanks guys!

**Pull request closed without merging**
