### PR TITLE
Office 365/SharePoint Online starter intranet solution

### PR DESCRIPTION
**Pull request by FranckyC**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| New sample?      | yes

#### What's in this Pull Request?

This solution aims to provide the fundamental building blocks of a common intranet solution with SharePoint Online/Office 365 through a lightweight client side solution using and the latest web stack development tools and frameworks.

This solution has been converted to a generic solution from a real-world project.

The functional documentation is available [here](http://thecollaborationcorner.com/2016/08/22/part-1-functional-overview-how-to-use-the-solution/).

### CODE REVIEW

**Comment by FranckyC** [comment]
The temporary password to access the [documentation](http://thecollaborationcorner.com/2016/08/22/part-1-functional-overview-how-to-use-the-solution) is "**pnp**"

**Comment by VesaJuvonen** [comment]
thx Franck, this looks really interesting and is highly needed sample around building publishing intranets using client side techniques. We'll have a look and get it included in the library for the September release. Will let you know if there's anything specific to address.

**Comment by FranckyC** [comment]
Ok thanks Vesa! Let me know if you need something else.

**Comment by AntosTech** [comment]
This is great and much needed. I am eager to test it on my own environment. One of the challenges we have been facing is branding O365 and SP2013 on-prem. The navigation is not so easy to manipulate. Our users want the megamenu capability on both environments.

**Comment by FranckyC** [comment]
@AntosTech I didn't test this solution for On-Prem environments but I'm pretty sure it will work (this is just client-side code). However, don't forget to download the On-Premise version of the PowerShell PnP cmdlets accordingly.

**Comment by FranckyC** [comment]
Please use the PowerShell June 2016 Intermediate 3 cmdlets version (https://github.com/OfficeDev/PnP-PowerShell/releases/tag/2.5.1606.3). I had some issues with the last version (August). After deployment, only a blank page is displayed.

**Comment by FranckyC** [comment]
@VesaJuvonen Is everything ok?

**Comment by VesaJuvonen** [comment]
We are looking to get this merged in September master merge, which will happen this Friday - meaning that target to get this checked is early this week. Sorry for the delay.

**Comment by VesaJuvonen** [comment]
Thx Franck, absolutely brilliant work on showing multiple different aspects in one solution. Would be you available for doing 10-15 min demo on this during our next monthly call on Tuesday 13th of September? - Would be great to do a quick demo on this. This is also absolutely potential PnP Webcast topic to explain the solution and how it works - but would like to start with the monthly call, if that works for you.

**Comment by FranckyC** [comment]
Thanks @VesaJuvonen ! Sure, I can do a quick demo of this solution during the next call. Let me know.

**Comment by VesaJuvonen** [comment]
thx Frank for that. This is the recurrent monthly PnP call and you can download invite from http://aka.ms/sppnp-call. We'll get you noted in the agenda communicated as part of the monthly release and then book that 10-15 min time for showing this in practice.

**Comment by alirobe** [comment]
q: this solution uses a custom .master file, I thought that was against best practice?

**Comment by FranckyC** [comment]
Hi @alirobe 

To be short on this:

- If you use SharePoint as an « operational » day-to-day tool with team sites, business features, etc., I totally agree to not modify the master page, because it makes no sense. In this case, it is considered as a bad practice because your users won't benefit of the latest UI upgrades.
- If you use SharePoint as a publishing portal, which is the case here, you probably might want your portal looks like something different from the ugly default SharePoint theme. Let’s be clear here: if you want a beautiful and mobile design, for now, you have to modify the master page, even for few HTML markup modifications (and this is not a shame). This is your image, your graphic identity so what’s the problem? For your information, I tried to not update the master page in the first place, but I rapidly figured out that it was almost impossible for my use case (mobile + components based approach).

Finally, if you plan to build an intranet solution using SharePoint Online, maybe this solution is not the best option for you right now because the UI may change drastically soon. However, for an on-premise solution, this solution may be a good starter option to build a mobile client-side intranet.

**Comment by alirobe** [comment]
@FranckyC, good to hear. Thanks for a great solution.

**Pull request merged**
