### PR TITLE
A set of reusable/extendable taxonomy navigation components for SharePoint Online

### PR DESCRIPTION
**Pull request by FranckyC**
Sample of taxonomy navigation reusable/extendable components (main menu, contextual menu and breadcrumb) for SharePoint Online using JSOM, Office UI Fabric and modern JavaScript libraries like Knockout JS, Require JS and Amplify JS.

All the installation procedure is in the README file.

I think it can be useful for other developers, not only for navigation menus themselves, but also for the underlying component provisioning approach.

Don't hesitate if you have some questions!

Thank you.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Franck, looks really good. We'll get this merged by the March release.

**Comment by FranckyC** [comment]
Thanks! Let me know if there is anything else to update (README or other).

**Comment by VesaJuvonen** [comment]
Hi - we'll have a look on this soon and should be fine for March release. Would you be available for 10-14 min demo in the monthly community call around this? Call is on 8th of March at 8 AM PST.

**Comment by FranckyC** [comment]
Hi. Yes for sure!

**Comment by patrick-rodgers** [comment]
Looks good, very happy to have the contribution, thanks @FranckyC!

**Pull request merged**
