### PR TITLE
Added Widget Wrangler

### PR DESCRIPTION
**Pull request by BobGerman**
Added Widget Wrangler to Core.JavaScript and Provisioning.Microsurvey

Per our conversation with Patrick Rodgers, Julie Turner, Bob German on 12/10/2015, we are adding Widget Wrangler to the JS Core. We have our own readme file (pnp-ww.md) and are glad to help incorporate it with the main readme as appropriate.

Thanks!

### CODE REVIEW

**Comment by BobGerman** [comment]
Hey Patrick - we found a minor issue in the documentation (pnp-ww.md) ... can I sneak in a small change as well? I'll email you ... thanks!

**Comment by patrick-rodgers** [comment]
Hi @BobGerman 

Just seeing this, are you ready for us to merge this PR or do you have a few changes still to make? Let me know and we can review and merge.

Thanks,

Patrick

**Comment by BobGerman** [comment]
Thanks Patrick - there is a 1 line change in the documentation. Should I do
a 2nd PR with the change or just send it to you?

I'm not sure if you have to massage the documentation anyway.

 

Thanks!

**Comment by BobGerman** [comment]
We can close this PR and you can submit a new one with everything or you can submit a second with the new changes, either works. Once you say they are ready I will review and let you know if we need any changes to the script or docs.

Thanks,

Patrick

From: Bob German [mailto:bgerman1@hotmail.com]
Sent: Monday, December 21, 2015 10:03 AM
To: 'OfficeDev/PnP' <reply@reply.github.com>; 'OfficeDev/PnP' <PnP@noreply.github.com>
Cc: Patrick Rodgers <Patrick.Rodgers@microsoft.com>
Subject: RE: [PnP] Added Widget Wrangler (#1259)

Thanks Patrick - there is a 1 line change in the documentation. Should I do a 2nd PR with the change or just send it to you?
I'm not sure if you have to massage the documentation anyway...

Thanks!

**Comment by BobGerman** [comment]
OK, I updated my pull request and fixed the documentation.

(The ww-appName attribute is required, and that should now be documented
correctly. We want to remove the requirement in a future version for
non-Angular widgets.)

 

Thanks!

 

From: Patrick Rodgers [mailto:Patrick.Rodgers@microsoft.com] 
Sent: Monday, December 21, 2015 11:24 AM
To: Bob German <bgerman1@hotmail.com>; 'OfficeDev/PnP'
<reply+00472b08e0f01f648a4026abd695a19683f70319f1031cdb92cf00000001128bcc5c9
2a169ce074db161@reply.github.com>; 'OfficeDev/PnP' <PnP@noreply.github.com>
Subject: RE: [PnP] Added Widget Wrangler (#1259)

 

We can close this PR and you can submit a new one with everything or you can
submit a second with the new changes, either works. Once you say they are
ready I will review and let you know if we need any changes to the script or
docs.

 

Thanks,

 

Patrick

 

From: Bob German [mailto:bgerman1@hotmail.com] 
Sent: Monday, December 21, 2015 10:03 AM
To: 'OfficeDev/PnP'
<reply+00472b08e0f01f648a4026abd695a19683f70319f1031cdb92cf00000001128bcc5c9
2a169ce074db161@reply.github.com>; 'OfficeDev/PnP' <PnP@noreply.github.com
<mailto:PnP@noreply.github.com> >
Cc: Patrick Rodgers <Patrick.Rodgers@microsoft.com
<mailto:Patrick.Rodgers@microsoft.com> >
Subject: RE: [PnP] Added Widget Wrangler (#1259)

 

Thanks Patrick - there is a 1 line change in the documentation. Should I do
a 2nd PR with the change or just send it to you?

I'm not sure if you have to massage the documentation anyway.

 

Thanks!

**Pull request merged**
