### PR TITLE
WebExtensions.InstallSolution root Web.RootFolder was not initialised

### PR DESCRIPTION
**Pull request by braegelno5**
Microsoft.SharePoint.Client.AppModelExtensions.InstallSolution 
- rootWeb.RootFolder was not initialised -> throws an error, fixed
- check for error msg changed, because msg is sometimes localized in front of the guid
- the DeleteObject() is also running on the new initialised rootFolder object
(for testing you should uncomment [Ignore()] on WebExtensionsTests.InstallSolutionTest)

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Torsten,

Thanks a lot for this contribution! 

Before we can accept your changes we would need to ask you to sign a [collaboration agreement](https://github.com/OfficeDev/PnP/blob/dev/Microsoft%20Corporation%20Collaboration%20Agreement-Officedev%20Patterns%20%26%20Practices%20GetHub%20Project.docx). Can you please fill in the sections highlighted in yellow, sign it and send a scanned version to Office365PnP_CA@microsoft.com.

**Comment by braegelno5** [comment]
Hi Bert,
I have attached the scanned and signed agreement as PDF.
:-)TSC from mobile.
--

**Comment by jansenbe** [comment]
Sorry Torsten, but I don't see the document. Can you please mail it to Office365PnP_CA@microsoft.com?

**Comment by jansenbe** [comment]
Thanks for this contribution Torsten. We've received the contributor agreement and have merged the change you've proposed.

**Pull request merged**
