### PR TITLE
Initial Commit of Mobile Sample

### PR DESCRIPTION
**Pull request by SPDoctor**
Mobile Office 365 REST API cross-platform sample using Apache Cordova and ADAL Cordova plugin to obtain access token.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Bill, we'll have a look on this during up coming days. Target is to get it merged for the April release.

**Comment by VesaJuvonen** [comment]
thx Bill. Sorry for the delay on this one. Resourcing challenges.

**Comment by VesaJuvonen** [comment]
Missed this one - just to group this one with other Microsoft Graph samples, renamed the folder slightly. Now located in https://github.com/OfficeDev/PnP/tree/dev/Samples/MicrosoftGraph.Cordova.Mobile

**Comment by SPDoctor** [comment]
Thanks. Wasn't sure about the name.

**Pull request merged**
