### PR TITLE
Added sample integration of WebApi and SPOnline using OAuth on behalf of user

### PR DESCRIPTION
**Pull request by RARomano**

### CODE REVIEW

**Comment by SchauDK** [comment]
Great sample.
Any suggestions on how to make this multitenant.

**Comment by VesaJuvonen** [comment]
Hi Rodrigo, sorry for small delay on getting this in due vacation times cross team, but we should have progress on pull requests in near future.

**Comment by RARomano** [comment]
Hi Vesa,

NP at all. I really want to contribute more.. How does the activities assignment works?

**Comment by RARomano** [comment]
Hi @SchauDK, I've never tried this sample in multitenant mode. I'm not sure if it works.

**Pull request merged**
