### PR TITLE
Branding.js link

### PR DESCRIPTION
**Pull request by MartinHatch**
Updated code samples to include MDS (and non-MDS) site support

### CODE REVIEW

**Comment by jansenbe** [comment]
Thanks Martin!

**Comment by jansenbe** [comment]
Hi Martin,
I've merged this...but somehow it's not yet working correctly. Navigating from for the google maps list to the color list and back to the google maps list causes the google maps list not to render anymore. Do you see this as well in your testing?

**Comment by MartinHatch** [comment]
Might be a caching issue as the files / paths are the same.

Have you tried deploying to a new Site Collection?

**Comment by MartinHatch** [comment]
@jansenbe In which environment specifically are you seeing this? (SP2013 or SPO?)

I have just deployed the WSP to a brand new Site Collection and am not seeing that issue occur.

**Comment by MartinHatch** [comment]
@jansenbe ok just seen this on an SPO site. I'll investigate .. not sure whats wrong

**Comment by jansenbe** [comment]
I've been testing in SPO only

**Pull request merged**
