### PR TITLE
Visual Studio extension sample for PnP template provisioning

### PR DESCRIPTION
**Pull request by jcfetzer**
This sample demonstrates using the PnP provisioning engine within a Visual Studio extension package to assist with common deployment tasks for SharePoint assets. The VSTools extension package maintains the PnP provisioning engine XML file automatically as files are added or removed from the project instead of the developer having to fill out the file manually which usually results in missing items, misspelled items, etc. In addition to the XML file, the extension package also provides some useful developer shortcuts such as right-click to quickly deploy a file (rather than all items in the XML file) and right-click to quickly deploy the entire provisioning template. The PnP provisioning engine XML file is fully supported (ie: content types, site columns, etc.) and deployable, however the extension package only maintains file references within this XML file at this time.

### CODE REVIEW

**Comment by jansenbe** [comment]
Thanks for this Jerry. 

We've not yet merged this one as we're still deciding on the right place to put this. We're looking into a PnP-Tools repository...we'll keep you updated.

**Comment by VesaJuvonen** [comment]
We are looking into getting official PnP Core component signed with future releases, which is required for the VS tools. That will help on getting this one properly packaged. We are targeting to have signing in the January release of the PnP, so we'll process this slightly later with re-locating it to the new PnP tools repository.

Looks really good and great contribution.

**Comment by jcfetzer** [comment]
Thanks for the updates!

**Comment by navarrorc** [comment]
Hi Jerry,
I'm urgent need to look at your code to perhaps implement in an Enterprise solution I'm working on for a client. How can I get a hold of your Provisioning.VSTools project? When I clone the repo from your github page it does not contain the project under samples. send me a tweet at @navarrorc and we can chat if you have time to help me out. Thanks in advance.

**Comment by erwinvanhunen** [comment]
Hi! 

I'm currently evaluating this sample and I love the idea of having an extension that can help developers build provisioning solutions using the PnP Engine. However, I run into a few issues:

1. The VSIX manifest is set to only allow to install the extension on Visual Studio Pro 12. Is there a specific reason you limit it to this? In order for me to install it I had to update the manifest to allow for installation on Visual Studio Enterprise 2015.
2. The fact that one needs to sign the solution with a valid certificate will hinder many developers to successfully deploy this solution if they want to build it themselves, but that's something you point out in the readme.md too.
3. Is it possible to look into another way to store the credentials? Right now you require to add the user credentials to the configuration file in clear text. That's not really something we should do. Consider looking into encrypting the credentials or using the Windows Credential Manager to store them.
4. I built the solution, signed it with a certificate, installed it. Then I create a new project, activated the extension to it and addied a valid template file to it. I created a resources folder and modified the config to point to the template and folder. I added a file to the resources folder and the extension updates the template file from valid XML into ```
㼼浸⁬敶獲潩㵮ㄢ〮㼢ാ㰊湰㩰牐癯獩潩楮杮砠汭獮瀺灮∽瑨灴⼺猯档浥獡搮癥漮晦捩⹥潣⽭湐⽐〲㔱〯⼸牐癯獩潩楮杮捓敨慭㸢਍†瀼灮债敲敦敲据獥䜠湥牥瑡牯∽晏楦散敄偶偮䌮牯ⱥ嘠牥楳湯ㄽ㠮ㄮㄱ⸵ⰰ䌠汵畴敲渽略牴污‬畐汢捩敋呹歯湥挽㌲㡤㠰て晢㈸㉥∳⼠ാ 㰠湰㩰敔灭慬整⁳䑉∽佃呎䥁䕎ⵒ䕔偍䅌䕔㔭㜴䌴〰䌲㑁㐳㌳㠵䉃䕃ぃぁ䔶㠰㈷∹ാ †㰠湰㩰牐癯獩潩楮杮敔灭慬整䤠㵄吢䵅䱐呁ⵅ㐵㐷ぃ㈰䅃㌴㌴㔳䌸䍂䍅䄰㘰ぅ㜸㤲•敖獲潩㵮ㄢ㸢਍†††瀼灮区捥牵瑩㹹਍††††瀼灮债牥業獳潩獮⼠ാ ††㰠瀯灮区捥牵瑩㹹਍†††瀼灮䘺慥畴敲⁳㸯਍†††瀼灮䘺汩獥ാ †††㰠湰㩰楆敬匠捲∽慊慶捓楲瑰⸱獪•潆摬牥∽•癏牥牷瑩㵥琢畲≥⼠ാ ††㰠瀯灮䘺汩獥ാ †㰠瀯灮债潲楶楳湯湩呧浥汰瑡㹥਍†⼼湰㩰敔灭慬整㹳਍⼼湰㩰牐癯獩潩楮杮
``` e.g that 's not really working :-) I wonder if you have seen this before?

I understand this is a first release, but a few things I think need to be fixed before we can merge this in the PnP repo. In a future release I would love to see a more UI based approach to store settings for the tool, instead of an XML based approach. Especially the fact that the configuration file contains a userid and password will hinder people in using it en environment with many developers where each dev has his own tenant to work towards too. One would have to exclude the file from source control somehow, which requires an additional action.

**Comment by erwinvanhunen** [comment]
Hi! I was wondering if you had the time looking into the reply I wrote. We're still interested in making this work.

**Comment by VesaJuvonen** [comment]
Hi, just to ping the thread. There's a question in the above comments. This is interesting stuff, which we would like to gradually get included in the tools.

**Comment by jcfetzer** [comment]
Hi, my apologies...I did not see the posts to this thread until this morning.  I will provide feedback on the questions shortly.  Sorry for the delay.

**Comment by VesaJuvonen** [comment]
thx Jerry, just a ping. :-)

**Comment by jcfetzer** [comment]
- 1.  The VSIX manifest is set to only allow to install the extension on Visual Studio Pro 12. Is there a specific reason you limit it to this? In order for me to install it I had to update the manifest to allow for installation on Visual Studio Enterprise 2015.

**Jerry – I built the package on VS Pro 2013 (v 12.0) so that’s what the manifest set as the install target.  I'm working on testing with VS 2015.**

- 2. The fact that one needs to sign the solution with a valid certificate will hinder many developers to successfully deploy this solution if they want to build it themselves, but that's something you point out in the readme.md too.

**Jerry - The signing requirement is per VSIX packages.  If/when the PnP assemblies are signed then this will not be an issue.**

- 3.	Is it possible to look into another way to store the credentials? Right now you require to add the user credentials to the configuration file in clear text. That's not really something we should do. Consider looking into encrypting the credentials or using the Windows Credential Manager to store them.

**Jerry - Yes this was considered, however given time constraints it was not able to be implemented at the time.**

- 4.	I built the solution, signed it with a certificate, installed it. Then I create a new project, activated the extension to it and addied a valid template file to it. I created a resources folder and modified the config to point to the template and folder. I added a file to the resources folder and the extension updates the template file from valid XML into  㼼浸⁬敶獲潩㵮ㄢ〮㼢ാ㰊湰㩰牐癯獩潩楮杮砠汭獮瀺灮∽瑨灴⼺猯档浥獡搮癥漮晦捩⹥潣⽭湐⽐〲㔱〯⼸牐癯獩潩楮杮捓敨慭㸢਍†瀼灮债敲敦敲据獥䜠湥牥瑡牯∽晏楦散敄偶偮䌮牯ⱥ嘠牥楳湯ㄽ㠮ㄮㄱ⸵ⰰ䌠汵畴敲渽略牴污畐汢捩敋呹歯湥挽㌲㡤㠰て晢㈸㉥∳⼠ാ 㰠湰㩰敔灭慬整⁳䑉∽佃呎䥁䕎ⵒ䕔偍䅌䕔㔭㜴䌴〰䌲㑁㐳㌳㠵䉃䕃ぃぁ䔶㠰㈷∹ാ †㰠湰㩰牐癯獩潩楮杮敔灭慬整䤠㵄吢䵅䱐呁ⵅ㐵㐷ぃ㈰䅃㌴㌴㔳䌸䍂䍅䄰㘰ぅ㜸㤲•敖獲潩㵮ㄢ㸢਍†††瀼灮区捥牵瑩㹹਍††††瀼灮债牥業獳潩獮⼠ാ ††㰠瀯灮区捥牵瑩㹹਍†††瀼灮䘺慥畴敲⁳㸯਍†††瀼灮䘺汩獥ാ †††㰠湰㩰楆敬匠捲∽慊慶捓楲瑰⸱獪•潆摬牥∽•癏牥牷瑩㵥琢畲≥⼠ാ ††㰠瀯灮䘺汩獥ാ †㰠瀯灮债潲楶楳湯湩呧浥汰瑡㹥਍†⼼湰㩰敔灭慬整㹳਍⼼湰㩰牐癯獩潩楮杮  e.g that 's not really working :-) I wonder if you have seen this before?

**Jerry – I have not seen this before but am investigating.**

I understand this is a first release, but a few things I think need to be fixed before we can merge this in the PnP repo. In a future release I would love to see a more UI based approach to store settings for the tool, instead of an XML based approach. Especially the fact that the configuration file contains a userid and password will hinder people in using it en environment with many developers where each dev has his own tenant to work towards too. One would have to exclude the file from source control somehow, which requires an additional action.

**Jerry - Yes, UI settings interface was considered, however given time constraints it was not able to be implemented at the time.**

I'm working with some others to investigate these items and will report back once I have some information.

**Comment by miket9884** [comment]
Hi everyone - we have been coordinating internally to make the changes to address some of the points in these comments... we haven't merged our latest changes yet, but they include the items below.

- using the latest nuget for OfficeDevPnP.Core.Online (so we aren't using an old copy of the dll that we signed ourselves since the older versions the dll were not signed)
- created a simple dialog for editing the site url & user/password
- saved the user credentials to a separate .user file (with the password encrypted)
- made the call that applies the provisioning template asynchronous so the Visual Studio UI doesn't freeze up while deploying

We're testing these changes out internally this week and hoping to merge them in soon... we have many other ideas on what we'd like to incorporate here in the long run but not really sure on timing yet.  We'll keep you posted when we're done testing, we would really like to see this merged into the official PnP repository if all goes well.  Thanks!

**Comment by VesaJuvonen** [comment]
thx Michael for the update.

**Comment by jcfetzer** [comment]
Hi Everyone, the latest changes and updates per Michael have been tested and merged into this branch.  Thanks.

**Comment by VesaJuvonen** [comment]
thx Jerry. We'll have a look on this soon.

**Comment by jcfetzer** [comment]
Hi Vesa, any questions? Or status of merging?  Thanks!

**Comment by miket9884** [comment]
Hi Vesa - just following up... any idea on timing for merging this or if there are some issues preventing the merge?  thanks

**Comment by VesaJuvonen** [comment]
Really sorry around the delay. We are trying to figure out where this should be landing in Core team, so that it can be easily maintained. We have not forgotten you. :-)

**Comment by jcfetzer** [comment]
Thanks for the update

**Comment by VesaJuvonen** [comment]
Sorry for the delay on this. This is one of those hard ones. Tool looks really promising and we would like to absolutely have this kind of tool for the benefit of the community. There's two key things to agree on.

1. Are we committed on updating and keep on evolving this? - if we are, this is absolutely welcome to the PnP
2. Most suitable location would be PnP-Tools repository if we agree that there's enough commitment on keeping evolving this

I'm sure that community will absolutely assist on this, when they realize the value, but we in the Core team do not really have availability on start evolving this tool at least right now. This means that we would be looking initially commitment from your side on this and then getting more people involved. 

Thoughts?

**Comment by miket9884** [comment]
Hi Vesa - I am interested in evolving this tool... I know from the last community call that there were some details about upcoming changes in how files and folders are provisioned so we'll need to see how that impacts what we have here.  There are some improvements that we'd like to make as well at some point... we are interested in continuing to evolve and improve this as long as it's relevant.  

For what it's worth, I have a small team that is currently using this add-in successfully for both development and also now using continuous integration via Visual Studio Team Services (with the help of a simple console app)... the ability to edit and deploy easily in Visual Studio is great with the added benefit that I can use the same exact template for continuous integration deployments.

**Comment by VesaJuvonen** [comment]
thx Michael and Jerry,
To enable easier editing and evolving of this tool, I'd suggest that we relocate the solution under PnP-Tools. We do not have dev branch there and we can move much faster on the PRs in that side. Since this is also more like a tool, PnP-Tools repository would be then more suitable location. We'll then link this to PnP pages in the dev.office.com and in our communications.

I'll close this PR now and would suggest that you re-locate this to PnP-Tools at https://github.com/OfficeDev/PnP-tools - right location would be under the Solutions in that repository. We will then get the PR finally fully merged and get you guys some visibility on this - Sounds good? Obviously we'll keep on them processing any changes on this in fast manner in future.

On that company promotion - Are you fine for using your company logo in our May release notes? We are looking to give credits not only for specific users, but also to have the company logo they work in starting from May release.

Thx for this contribution beforehand. This is really cool add-on and will be certainly used by community as long as they can find it... and let's make sure that they do.

**Comment by miket9884** [comment]
Thanks Vesa, that sounds like a good plan... I'm not sure if we'll get around to moving it this week but we will follow up as soon as possible.  Regarding company promotion, using our logo would be great thank you for considering this.

**Comment by jcfetzer** [comment]
Thanks Vesa and Mike!

**Pull request closed without merging**
