### PR TITLE
SiteCollection Provisioning O365 App

### PR DESCRIPTION
**Pull request by rovcaene**
This sample demonstrates an Office 365 app through which you can create site collections in SharePoint Online. For more information, you can look at the README.md.

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Robrecht, thanks for your contribution...great to see some input coming from Belgium :).

In PnP we currently have several provisioning samples which results in people having trouble finding the right sample. We truly value your contribution, but to avoid even more confusion we would like to understand what makes this sample unique. Depending on your feedback we can see how we can best process your contribution: might be that it's better to add some of the "new" elements into the existing provisioning samples.

Hope you can understand.

**Comment by rovcaene** [comment]
Hello Bert, this solution was developed in february 2015, and it wasn't until the Ignite conference that we (colleague and I) talked about this sample to Vesa and if it would be a good addition to the PnP samples. 
Vesa reviewed the solution and sent my colleague a message on Yammer saying that it was a good sample and that we should add it to the PnP structure under Samples with the name "Provisioning.Cloud.Management".

That is why I took the time to add it to the PnP project. I perfectly understand that there might be better solutions available in the current PnP project right now.

Greetings

**Comment by jansenbe** [comment]
Hi Robrecht, we really appreciate your contribution but we've decided to not merge this one. We already have way too many provisioning samples due to historical reasons which is causing confusion for the PnP users. Adding even more will not help. If you feel a particular feature of your sample is not covered elsewhere then please let me know...would be better to extend an existing sample in that case and I can help you with that.

Hope you understand.

Best regards,
The pnp core team

**Comment by VesaJuvonen** [comment]
Hi Robrecht also from my behalf. This was indeed really nice implementation, but right now we almost have already too many samples around the provisioning side of the add-in model. This is why we decided to decline this submission. We would rather see improvements on existing ones to avoid further confusion for the community.

Contribution is absolutely appreciated and like Bert mentioned, if you see something what's not included in the existing sample or in the PnP provisioning engine, we would absolutely be interested on your input on this effort. You clearly have experience on provisioning models.

Best regards,
Vesa Juvonen

**Pull request closed without merging**
