### PR TITLE
Taxonomypicker

### PR DESCRIPTION
**Pull request by vlad0**
Fixed several things in the taxonomypicker as follow:
- documentation <div> wrapper is required by the logic
- indenting of the terms wasn't working because of wrong value in css
- Suggestions list wasn't populated when no filterTermId was added
- External click not fired when this._dialog == null

### CODE REVIEW

**Comment by jansenbe** [comment]
Thanks a lot for this contribution! 

Before we can accept your changes we would need to ask you to sign a [collaboration agreement](https://github.com/OfficeDev/PnP/blob/master/Microsoft%20Corporation%20Collaboration%20Agreement-Officedev%20Patterns%20%26%20Practices%20GetHub%20Project.docx). Can you please fill in the sections highlighted in yellow, sign it and send a scanned version to Office365PnP_CA@microsoft.com. This agreement only needs to be signed once, so for all your future pull requests you're fine. Sorry for the extra hassle, but it is a new requirement from our legal department.

**Comment by SharePointRadi** [comment]
Bert, Vlado is from my company, would our agreement count?

**Comment by vlad0** [comment]
Actually I've already signed & sent it to the email :)

**Comment by jansenbe** [comment]
Hi Vlad, I'll be looking into this.

**Comment by jansenbe** [comment]
Hi Vlad,

You've done your improvements in the sample, but the latest version of the taxonomy picker is https://github.com/OfficeDev/PnP/tree/dev/Components/Core.TaxonomyPicker. This one has had several changes of the last months (e.g. perf improvements). Would it be possible for you to merge your changes in this version of the control...and then update the control in the sample to get them back aligned?

If not then please let me know and I'll have a look at that.

**Comment by vlad0** [comment]
I'll merge them :)

**Comment by jansenbe** [comment]
Thanks a lot!

**Comment by vlad0** [comment]
Hi again. 

The difference between the Component and the Sample are the following options/parameters:
filterTermId – the GUID of the term which will be used to filter terms from Term Set for cascading (it is optional parameter)
useTermSetasRootNode – Boolean value indicating whether to display term set as root node in the selection control (it is optional parameter)
levelToShowTerms – Numeric value indicating how many level of cascading controls are being displayed

Should I merge them in the Component Taxonomypicker?

**Comment by jansenbe** [comment]
Yes please. The goal is to have a single taxonomy picker which we'll 'maintain' inside the components project. For the samples project we should clearly indicate in the documentation that this is a copy of the components one and that all changes to the taxonomypicker should be done on the component one.

**Comment by jansenbe** [comment]
Closing this one for now based on discussion with @SharePointRadi . If you want to get these changes in please create a new PR based upon the taxonomy picker control in the components folder. Thx;

**Pull request closed without merging**
